### ISSUE TITLE
'updateEntry' is already declared in the upper scope on line 30 column

### ISSUE THREAD

**Issue by margittennosaar** [jasondansie/react-tasteit#7]
https://github.com/jasondansie/react-tasteit/blob/de103f3b92b10054ba4ed9631478f758a374ae83/storage/storageLayer.js#L30

Shadowing is when a local variable shares the same name as a variable in its scope. This can cause confusion while reading the code, making accessing the global variable impossible.

**Comment by jasondansie** [comment]
I normally try not to do this because it confuses me too. Weird that I did it here. I fixed it so no more confussion.
