### ISSUE TITLE
'__dirname' is not defined

### ISSUE THREAD

**Issue by margittennosaar** [jasondansie/react-tasteit#8]
https://github.com/jasondansie/react-tasteit/blob/de103f3b92b10054ba4ed9631478f758a374ae83/server.js#L18

Multiple warnings about '__dirname' is not defined in this file. 

This rule can help you locate potential ReferenceErrors resulting from misspellings of variable and parameter names or accidental implicit globals (for example, from forgetting the var keyword in a for loop initialiser).

**Comment by jasondansie** [comment]
This too is right from Illka's leasons. when I do a console log of the storageFilePath it give the proper dir listing and no errors.  How or where are you seeing this error come up? I did just to a check with eslint and it too does not find any errors.
